### ISSUE TITLE
Atualização do e-mail do setor que é enviado para o aluno

### ISSUE THREAD

**Issue by ogustavobrandao** [lmtsufape/solicita-2.0#109]
Atualmente, o e-mail do setor que está cadastrado no Solicita para o aluno, que, inclusive, ele pode entrar em contato em caso de dúvidas, é o drca@ufape.edu.br. Precisamos alterar, pois o setor responsável pela emissão de documentos agora é a Coordenadoria de Graduação. O e-mail para contato deve ser alterado para cgrad.drca@ufape.edu.br

**Comment by felipe-rodriguess** [comment]
Só atentar que o e-mail é o cgrad.drca@ufape.edu.br, tem um "para" aí no início que não faz parte do e-mail.

**Comment by ogustavobrandao** [comment]
Blz, Felipe. Fiz a correção do texto. Como eu copiei do doc que foi enviado acabou que quando coloquei no texto da issue ficou desformatado. Agradeço pelo comentário!
