### ISSUE TITLE
Solicitação de desbloqueio do Siga

### ISSUE THREAD

**Issue by Rener1** [lmtsufape/solicita-2.0#115]
Criar uma opção onde o aluno possa requerer o desbloqueio do Siga.

**Comment by felipe-rodriguess** [comment]
**FUNCIONALIDADE PARA O ALUNO:**
Um botão onde o aluno clica e gera um pedido de desbloqueio.


**FUNCIONALIDADE PARA O SERVIDOR:**
- Listar os pedidos de desbloqueio com o NOME, CURSO, CPF (só números, sem ponto e nem hífen), com filtro para listar por ordem alfabética ou ordem do pedido.
- Após o servidor realizar o desbloqueio, ele clica em um botão com o nome DESBLOQUEADO, e o Solicita envia o seguinte e-mail para o aluno:

_Olá!

Seu SIGA foi desbloqueado. Para gerar novas senhas, siga o seguinte passo a passo:

1- Acesse: http://www.siga.ufape.edu.br
2- Digite seu CPF (somente números, sem traços e pontos) no campo login e não informe senha
3- Clique no botão "solicitar acesso" (do lado esquerda da tela)
4- Confira o CPF e clique em continuar
5- Leia as instruções, siga o passo-a-passo e informe os dados solicitados e, por fim, crie as senhas.

--
At.te
Departamento de Registro e Controle Acadêmico
> _
